@extends('errors.layout')
@section('title', __('No autorizado'))
@section('code', '401')
@section('img', '/img/noAutorizado.gif')
@section('message', __('No tienes autorización para realizar esta acción'))
