@extends('errors.layout')
@section('code', '404')
@section('title', __('Ooops!'))
@section('tit', 'Oooops, tenemos errores!')
@section('img', '/img/errorHomero.gif')
@section('message', __('El recurso solicitado no se ha encontrado o no existe'))
