@extends('errors.layout')
@section('title', __('Alto ahí!'))
@section('tit', 'Oooops, tenemos errores!')
@section('img', '/img/serverError.gif')
@section('message', __('Problemas de servidor, intenta de nuevo'))
